---
- name: Create HA Kubernetes cluster
  hosts: control_plane
  tasks:
    - name: Create cluster configuration
      ansible.builtin.shell: |
        kops create cluster \
        --name="jocluster.k8s.local" \
        --state="s3://jo-kops-state" \
        --zones="us-east-1a,us-east-1b" \
        --node-count=2 \
        --node-size=t3.medium \
        --control-plane-size=t3.medium \
        --yes
      args:
        executable: /bin/bash

    - name: Validate cluster
      ansible.builtin.shell: |
        kops validate cluster \
        --name="jocluster.k8s.local" \
        --state="s3://jo-kops-state" \
        --wait 10m
      args:
        executable: /bin/bash