---
- name: Create HA Kubernetes cluster
  hosts: control_plane
  vars:
    cluster_name: "{{ hostvars['localhost']['terraform_outputs']['cluster_name'] }}.example.com"
    state_store: "s3://{{ hostvars['localhost']['terraform_outputs']['kops_state_bucket'] }}"
  tasks:
    - name: Create cluster configuration
      ansible.builtin.shell: |
        kops create cluster \
        --name={{ cluster_name }} \
        --state={{ state_store }} \
        --zones={{ terraform_outputs.availability_zones | join(',') }} \
        --node-count=2 \
        --node-size=t2.micro \
        --master-size=t2.micro \
        --yes
      register: cluster_creation

    - name: Validate cluster
      ansible.builtin.shell: |
        kops validate cluster \
        --name={{ cluster_name }} \
        --state={{ state_store }} \
        --wait 10m